### ISSUE TITLE
Optionally have test runner exit on test failure

### ISSUE THREAD

**Issue by BNAndras** [RickBarretto/unitt#10]
Would it be possible to add a setting where the test runner immediately exits if any detected tests fail? That'd be useful for CI purposes.

**Comment by RickBarretto** [comment]
> Would it be possible to add a setting where the test runner immediately exits if any detected tests fail? That'd be useful for CI purposes.

Ohh, that is a good idea!
Right now it returns exit code, but at the end.
This is possible to suppress errors too, so you can call `runTests` multiple times in the same module.

But, haha! That is a good idea!
1. This makes it easy to find the error
2. This reduces the CI run time

**Comment by RickBarretto** [comment]
## Proposal

Implement an optional immediate return to be used in Continuous Integration.

## Syntax

```art
import {unitt}!

runTests.failFast "tests"
runTests.quickly "tests"
```

@BNAndras, I want you opinion about which one of the two is better. `failFast` or `quickly`?
Or even a better naming.

**Comment by RickBarretto** [comment]
Perhaps: `runTests.cease` or `runTests.desist`?

**Comment by RickBarretto** [comment]
Having a look into it, I'll need to change our current architecture.
Right now, `runTests` calls the testfiles from `execute`, and `test` prints immediately the `assert`'s result on the screen.

So, I'll need to create some `testSuit` value to store the tests, and make `test` return an object.
