### ISSUE TITLE
Show summary of tests passed/failed/skipped/detected

### ISSUE THREAD

**Issue by BNAndras** [RickBarretto/unitt#8]
The test runner should either report by default the number of tests passed, failed, skipped or detected (in case tests are misconfigured) or have that available as an option to be selected.

**Comment by RickBarretto** [comment]
Saving the last statistics, that is a good idea. 😉

**Comment by RickBarretto** [comment]
> The test runner should either report by default the number of tests passed, failed, skipped or detected (in case tests are misconfigured) or have that available as an option to be selected.

Re-reading your issue, I must ask you.
Are you talking about saving the last statistic to compare? Or are you talking about the final report of the current run?

Right now, this is reported: failed, skipped and passed tests, for the current run at the end of the process.

Obs.: This is shown by the `runTests` function.

**Comment by BNAndras** [comment]
My bad. I was talking about the current run after looking at the example in the repo readme. Feel free to close the issue.

**Comment by RickBarretto** [comment]
> My bad. I was talking about the current run after looking at the example in the repo readme. Feel free to close the issue.

No worries! Closing this!
